### ISSUE TITLE
More details

### ISSUE THREAD

**Issue by waldifubu** [mvrhov/mvrhovPhinxBundle#2]
Hi, I think your bundle could be useful.

But I need some more config details:
The _readme.md_ file is very skinny.

1. You have to add the bundle in Symfony's Appkernel.php to activate it
2. The config is missing completely. 

I need to know which data should be in parameters.yml and config.yml
Please add 'em in the README file.

Thanks in advance.

**Comment by mvrhov** [comment]
For starters you can look at the Configuration class.

**Comment by ghost** [comment]
I really wasted unnecessarily lot of time looking at Configuration.php so I've created a pull request #7 to address this
