### ISSUE TITLE
Namespace definitions not supported

### ISSUE THREAD

**Issue by spantaleev** [mvrhov/mvrhovPhinxBundle#9]
After https://github.com/cakephp/phinx/commit/14e36c5ce5540828a312f90dfbb5854fc15d3b73 (released as robmorgan/phinx 0.9.0), the [migrations template](https://github.com/cakephp/phinx/blob/14e36c5ce5540828a312f90dfbb5854fc15d3b73/src/Phinx/Migration/Migration.template.php.dist) in Phinx contains a `$namespaceDefinition` variable.

This bundle does not provide a substitution value for this parameter, so the migration files generated from the `phinx:create` console command contain `$namespaceDefinition` at the top of the file, making them invalid.

------

Thinking about it though, this bundle likely does too many things which it can avoid.
Instead of duplicating the Create command (in `\mvrhov\PhinxBundle\Command\CreateCommand`), it may just reuse Phinx's own Create command (from `\Phinx\Console\Command\Create`).

Likewise for all the other commands.

Had that been done, this `$namespaceDefinition` problem wouldn't have happened.

There's no point duplicating code that already exists and is maintained working upstream.

**Comment by mvrhov** [comment]
The commands are duplicated, because there is no easy way to rename command when it gets registered into the DIC.

Or at least there wasn't I'm not sure but maybe now from symfony 3.4 the "new" command name can be set when registering commands lazily into the DIC.

Nonetheless my plan is to deprecate this bundle as I've written my own migration tool that uses the SQL DDL directly (Phinx doesn't allow me to fully utilize the features of Postresql.).

**Comment by spantaleev** [comment]
You can change the command name like this:

```php
class CreateCommand extends \Phinx\Console\Command\Create {
	
	protected function configure() {
		parent::configure();

		$this->setName('phinx:create');
	}

}
```

Essentially, all the original command classes would only need a wrapper like this.

------

I understand about the bundle deprecation. Feel free to close these issues if you're going this way.

(I've since found out that Doctrine DB Migrations works well for my current use-case, so I've moved away from Phinx as well).

**Comment by mvrhov** [comment]
Oh, I do remember now. 
We need to inject data from the symfony container into the commands. However the phinx original commands want to parse the configuration file themselves. And there was no easy way to disable that.

**Comment by mvrhov** [comment]
FYI: I've released the mvrhov/migratum on monday
